-- Monitoring domain schema
-- Contains tables for application monitoring and logging

-- Error logging table
create table public.errors_log (
    id bigint primary key generated by default as identity (
        sequence public.errors_log_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
    ),
    message text not null,
    stack text,
    timestamp date
);

-- Enable Row Level Security
alter table public.errors_log enable row level security;