import { useEffect, useState, type ChangeEvent } from 'react';
import { Spinner, useDisclosure } from '@heroui/react';
import { Button, Input } from '@/components/ui';
import { PlusOutlined, TeamOutlined, SearchOutlined } from '@ant-design/icons';
import useOrganizations from './hook/useOrganizations';
import useAuth from '../auth/hooks/useAuth';
import type { Organization, OrganizationFormData } from './types/organizations';
import CreateOrganizationModal from './components/CreateOrganizationModal';
import OrganizationCard from './components/organization-card';
import { useTranslation } from 'react-i18next';

export interface UserRoll {
    id: string;
    level: string;
    read: boolean;
    write: boolean;
    delete: boolean;
    invite: boolean;
    configure: boolean;
}

export default function Organizations() {
    const { t } = useTranslation();
    const { user } = useAuth();
    const { data: organizations, isLoading, error, createOrganization, mutate, getUserRolls } = useOrganizations(user?.id);
    const [searchTerm, setSearchTerm] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [formError, setFormError] = useState('');
    const [userRolls, setUserRolls] = useState<UserRoll[]>([]);

  

    useEffect(() => {
        mutate();
        { localStorage.removeItem('OrgName'); }

        getUserRolls().then(res => {
            if (res.error) {
                console.error(res.message);
                return;
            }
            const userRolls: UserRoll[] = res.data as UserRoll[] || [];
            const sortedRolls = userRolls.sort((a, b) => {
                const order = ["Lector", "Editor"];
                const aIndex = order.indexOf(a.level);
                const bIndex = order.indexOf(b.level);

                if (aIndex !== -1 && bIndex !== -1) {
                    return aIndex - bIndex;
                }
                if (aIndex !== -1) {
                    return -1;
                }
                if (bIndex !== -1) {
                    return 1;
                }
                return 0;
            })
            setUserRolls(sortedRolls);
        }).catch(err => {
            console.error(err);
        });
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // Form data state
    const [formData, setFormData] = useState<OrganizationFormData>({
        name: '',
        description: '',
    });

    // Modal states using useDisclosure
    const { isOpen: isCreateModalOpen, onOpen: onCreateModalOpen, onClose: onCreateModalClose } = useDisclosure();

    // Filter organizations based on search term
    const filteredOrganizations = organizations?.filter(
        (org: Organization) => org.name?.toLowerCase().includes(searchTerm.toLowerCase()) ?? false,
    );

    // Handle create form submit
    const handleCreateSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        if (!formData.name.trim()) {
            setFormError(t('organization_name_required_message'));
            return;
        }

        setIsSubmitting(true);
        setFormError('');

        // Find the admin roll
        const userRoll = userRolls.find(roll => roll.level === "Admin");

        try {
            if (!user?.id) {
                throw new Error(t('unauthenticated_message'));
            }

            const response = await createOrganization(
                formData.name.trim(),
                formData.description.trim(),
                '', // Slug will be generated by the backend
                user.id,
                userRoll ? userRoll.id : '',
            );

            if (response.error) {
                setFormError(response.message);
                return;
            }

            // Refresh organizations list
            mutate();
            onCreateModalClose();
        } catch (error) {
            setFormError(t('unexpected_error_message'));
            console.error(error);
        } finally {
            setIsSubmitting(false);
        }
    };

    // Handle form input change
    const handleInputChange = (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({
            ...prev,
            [name]: value,
        }));
    };

    // Handle create organization button click
    const handleCreateOrganization = () => {
        setFormData({
            name: '',
            description: '',
        });
        setFormError('');
        onCreateModalOpen();
    };

    if (isLoading) {
        return (
            <div className="flex justify-center items-center h-[calc(100vh-120px)]">
                <Spinner size="lg" />
            </div>
        );
    }

    if (error) {
        return (
            <div className="flex flex-col justify-center items-center h-[calc(100vh-120px)]">
                <p className="text-danger text-lg">{t('error_loading_organizations')}</p>
                <Button color="primary" className="mt-4" onClick={() => window.location.reload()}>
                    Try Again
                </Button>
            </div>
        );
    }

    return (
        <div className="overflow-y-auto h-full p-4 lg:p-6">
            <section className="pb-8 max-w-7xl mx-auto">
                <h1 className="text-2xl font-semibold">{t("your_organizations_title")}</h1>

                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", height: "100px", marginTop: "20px", marginBottom: "-40px" }}>
                    <div className="max-w-md h-10">
                        <Input
                            size='sm'
                            placeholder={t("search_organizations_placeholder")}
                            value={searchTerm}
                            type="search"
                            onChange={(e: ChangeEvent<HTMLInputElement>) => setSearchTerm(e.target.value)}
                            startContent={<SearchOutlined className="text-gray-400" />}
                            onClear={() => setSearchTerm('')}
                            isClearable
                            autoFocus
                        />
                    </div>
                    <div className="flex justify-between items-center create-workgroup-button">
                        <Button  startContent={<PlusOutlined />} onClick={handleCreateOrganization}>
                            {t("create_organization_button")}
                        </Button>
                    </div>
                </div>

                {filteredOrganizations?.length === 0 ? (
                    <div className="flex flex-col items-center justify-center py-16 px-4 border-2 border-dashed rounded-lg">
                        <TeamOutlined style={{ fontSize: '48px', color: '#888' }} />
                        <p className="mt-4 text-lg text-gray-600">
                            {searchTerm ? t("no_organization_matched_message") : t("no_organizations_found_message")}
                        </p>
                        {searchTerm ? (
                            <Button color="primary" variant="light" onClick={() => setSearchTerm('')} className="mt-2">
                                {t("clear_search_button")}
                            </Button>
                        ) : (
                            <Button color="primary" className="mt-4" onClick={handleCreateOrganization}>
                                {t("create_your_first_organization_message")}
                            </Button>
                        )}
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {filteredOrganizations?.map((org: Organization) => (
                            <OrganizationCard key={org.id} organization={org} userRolls={userRolls} />
                        ))}
                    </div>
                )}

                <CreateOrganizationModal
                    isOpen={isCreateModalOpen}
                    onClose={onCreateModalClose}
                    formData={formData}
                    handleInputChange={handleInputChange}
                    handleSubmit={handleCreateSubmit}
                    isSubmitting={isSubmitting}
                    formError={formError}
                />
            </section>
        </div>
    );
}
